// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZiG31sbDiVYVWM0LPvoEJ0SiCs1b2c74',
    appId: '1:344766618102:web:5b4f80f0f85f58b8288fd7',
    messagingSenderId: '344766618102',
    projectId: 'e-commerce-41888',
    authDomain: 'e-commerce-41888.firebaseapp.com',
    storageBucket: 'e-commerce-41888.appspot.com',
    measurementId: 'G-CEP328YQE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmWSuWoEdRhqD5k12tucFSl633glhtLEQ',
    appId: '1:344766618102:android:2c1747be3cd92206288fd7',
    messagingSenderId: '344766618102',
    projectId: 'e-commerce-41888',
    storageBucket: 'e-commerce-41888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQFEahG3AWZ_xBy6szRc1-oAItqilN4TQ',
    appId: '1:344766618102:ios:c3ccb963be38ab91288fd7',
    messagingSenderId: '344766618102',
    projectId: 'e-commerce-41888',
    storageBucket: 'e-commerce-41888.appspot.com',
    iosClientId: '344766618102-rofhtu01qje7d3uherkkisb61k44hirv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQFEahG3AWZ_xBy6szRc1-oAItqilN4TQ',
    appId: '1:344766618102:ios:c3ccb963be38ab91288fd7',
    messagingSenderId: '344766618102',
    projectId: 'e-commerce-41888',
    storageBucket: 'e-commerce-41888.appspot.com',
    iosClientId: '344766618102-rofhtu01qje7d3uherkkisb61k44hirv.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
